kind: Secret
apiVersion: v1
metadata:
  name: freedb-admin-secret
  namespace: default
data:
  oracle_pwd: Y2hhbmdlbWU=
type: Opaque
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: freedb
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: crc-csi-hostpath-provisioner
  volumeMode: Filesystem
---
#
# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: freedb
  namespace: default
spec:
  
  ## Use only alphanumeric characters for sid
  sid: FREE
  
  ## DB edition
  edition: free
  
  ## Secret containing SIDB password mapped to secretKey
  adminPassword:
    secretName: freedb-admin-secret

  ## Database image details
  image:
    ## Oracle Database Free is only supported from DB version 23.2 onwards
    pullFrom: container-registry.oracle.com/database/free:latest
    prebuiltDB: false

  ## size is the required minimum size of the persistent volume
  ## storageClass is specified for automatic volume provisioning
  ## accessMode can only accept one of ReadWriteOnce, ReadWriteMany
  persistence:
    size: 5Gi
    ## oci-bv applies to OCI block volumes. Use "standard" storageClass for dynamic provisioning in Minikube. Update as appropriate for other cloud service providers
    storageClass: crc-csi-hostpath-provisioner
    setWritePermissions: false
    accessMode: "ReadWriteOnce"

  ## Count of Database Pods. Should be 1 for free edition.
  replicas: 1